---
collections:
  - name: ansible.controller
    version: 4.1.1
  - name: redhat_cop.controller_configuration
    version: 2.1.1
  #windows
  - community.windows
  - name: ansible.windows
    version: 1.9.0