---
namespace: ansible
name: product_demos
version: 1.0.0
readme: README.md

authors:
  - Brian Addicks <baddicks@redhat.com

description: repository of demos to showcase Ansible features.

license:
  - GPL-3.0-or-later

tags:
  - apache
  - centos
  - rhel
  - el
  - amazon
  - linux
  - fedora
  - network
  - f5
  - developer
  - infrastructure
  - security
  - windows
  - opencap
  - insights
  - patching
  - tower
  - awx

build_ignore:
  - images
  - '*.tar.gz'

dependencies:
  "awx.awx": "*"

repository: https://github.com/brianaddicks/ansible-demo
documentation: https://github.com/brianaddicks/ansible-demo
homepage: https://github.com/brianaddicks/ansible-demo
issues: https://github.com/brianaddicks/ansible-demo/issues