---
- name: deploy new domain controller
  hosts: windows
  gather_facts: no

  tasks:

    - name: retrive AD Groups
      community.windows.win_domain_object_info:
        filter: objectClass -eq 'group'
        properties: name
      register: ad_groups

    - debug:
        #msg: "{{ ad_groups }}"
        msg: "{{ ad_groups | community.general.json_query('objects[*].Name') }}"