---
- name: deploy new domain controller
  hosts: windows
  gather_facts: no

  tasks:

    - name: retrive AD Groups
      community.windows.win_domain_object_info:
        filter: objectClass -eq 'group'
        properties: name
      register: ad_groups

    - debug:
        var: ad_groups