---
- name: deploy new domain controller
  hosts: windows
  gather_facts: no

  tasks:
    - name: Install ActiveDirectoryDsc PSModule
      win_psmodule:
        name: ActiveDirectoryDsc
        state: present

    - name: enable RDP
      win_dsc:
        resource_name: ADUser
        ensure: present
        username: "{{ sam_account_name }}"
        path: "CN={{ ou_path }},DC=ansible,DC=local"
        domainname: "{{ ad_domain }}"